name: deep-learning
channels:
  - defaults
  - conda-forge
dependencies:
  - pip=21.0.1
  - python=3.7.10
  - widgetsnbextension=3.5.1
  - ipywidgets=7.5.1
  - openssl=1.1.1
  - pip:
    - cachetools==4.2.2
    - h5py==2.10.0
    - importlib-metadata==4.0.1
    - joblib==1.0.1
    - keras==2.4.1
    - keras-preprocessing==1.1.2
    - kiwisolver==1.3.1
    - markdown==3.3.4
    - matplotlib==3.4.1
    - numpy==1.19.5
    - pandas==1.1.5
    - scikit-learn==0.24.2
    - scipy==1.6.3
    - seaborn==0.11.1
    - opencv-python==4.5.1.48
    - pydot==1.4.2
    - pydotplus==2.0.2
    - jupyter-contrib-core==0.3.3
    - jupyter-contrib-nbextensions==0.5.1
    - jupyter-highlight-selected-word==0.2.0
    - jupyter-latex-envs==1.4.6
    - jupyter-nbextensions-configurator==0.4.1
    - jupyter-timetracker==0.0.3
    - ipykernel==5.5.5
    - tensorflow==2.4.1
    - tensorflow-estimator==2.4.0
    - tensorboard==2.4.1
    - tensorboard-plugin-wit==1.8.0
